# Generated by Django 2.1.7 on 2020-03-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
