# Generated by Django 2.1.7 on 2020-05-08 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0002_auto_20200508_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='note_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
