# Generated by Django 2.1.7 on 2020-03-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundooapp', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue')], default='Blue', max_length=20)),
                ('is_archive', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
            ],
        ),
    ]
