# Generated by Django 2.1.7 on 2020-05-13 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundooapp', '0003_auto_20200508_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='collaborate',
            field=models.ManyToManyField(related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
