# Generated by Django 2.1.7 on 2020-05-14 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0004_note_collaborate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='collaborate',
            field=models.ManyToManyField(blank=True, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
