# Generated by Django 2.1.7 on 2020-06-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0006_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
