# Generated by Django 2.1.7 on 2020-06-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0007_auto_20200602_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
